import subprocess, os, sys

W, H, FPS = 1920, 1080, 30
FONT_BOLD = "/usr/share/fonts/truetype/google-fonts/Poppins-Bold.ttf"
FONT_LIGHT = "/usr/share/fonts/truetype/google-fonts/Poppins-Light.ttf"
RED = "0xB0202A"; DIM = "0x7C86AD"; WHITE = "0xF5F6FA"

SHOTS_DIR = "shots"
BUILD = "/tmp/build"; CLIPS = "/tmp/work/trailer"
SEGS = f"{BUILD}/segs3"
TXT = f"{BUILD}/txt3"
os.makedirs(SEGS, exist_ok=True)
os.makedirs(TXT, exist_ok=True)

PAD = 0.4  # crossfade dissolve length between every consecutive segment

def run(cmd):
    r = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    if r.returncode != 0:
        print("CMD FAILED:", " ".join(cmd))
        print(r.stdout.decode(errors="replace")[-4000:])
        sys.exit(1)

def txtfile(name, text):
    path = f"{TXT}/{name}.txt"
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    return path

IMG = {
    "home": f"{SHOTS_DIR}/shot-01-home.jpg",
    "building": f"{SHOTS_DIR}/shot-02-building-overview.jpg",
    "zonesOcc": f"{SHOTS_DIR}/shot-03-zones-occupied.jpg",
    "zoneDetail": f"{SHOTS_DIR}/shot-04-zone-detail-occupied.jpg",
    "automationLog": f"{SHOTS_DIR}/shot-05-automation-log.jpg",
    "accessService": f"{SHOTS_DIR}/shot-06-access-service.jpg",
    "accessEvents": f"{SHOTS_DIR}/shot-07-access-events.jpg",
    "investigationTop": f"{SHOTS_DIR}/shot-08-investigation-top.jpg",
    "investigationEvidence": f"{SHOTS_DIR}/shot-09-investigation-evidence.jpg",
    "commandCenter": f"{SHOTS_DIR}/shot-10-command-center.jpg",
}
SHORT_IMAGES = {"accessService"}

# ---- Timeline v3: merged segments (no narration-covering black, continuous camera moves,
#      SENSE..MONITOR now over dimmed real footage instead of pure black) ----
T = [
    {"t0":0.00, "t1":9.22,  "type":"clip","file":"massing.mp4"},
    {"t0":9.22, "t1":16.57, "type":"reveal"},
    {"t0":16.57,"t1":24.90, "type":"clip","file":"approach.mp4"},
    {"t0":24.90,"t1":30.43, "type":"shot","img":"building","ken":"in",
        "captions":[("ROOMS. ZONES. SENSORS. DEVICES.",24.90,30.43)]},
    {"t0":30.43,"t1":41.80, "type":"clip","file":"occupancy.mp4"},
    {"t0":41.80,"t1":49.30, "type":"clip","file":"projector.mp4"},
    {"t0":49.30,"t1":51.37, "type":"shot","img":"zoneDetail","ken":"hold",
        "captions":[("SMART LAB 301.",49.30,51.37)]},
    {"t0":51.37,"t1":58.95, "type":"shot","img":"zonesOcc","ken":"in","captions":[]},
    {"t0":58.95,"t1":67.93, "type":"clip","file":"hvac.mp4"},
    {"t0":67.93,"t1":77.40, "type":"shot","img":"automationLog","ken":"panfull",
        "captions":[
            ("THE DECISION IS MADE.",67.93,73.25),
            ("EVERY DECISION LEAVES A TRACE.",73.25,77.40),
        ],
        "subs":[("Command generated by the decision engine — physical execution status shown as reported.",67.93,73.25)]},
    {"t0":77.40,"t1":88.75, "type":"clip","file":"access.mp4"},
    {"t0":88.75,"t1":91.57, "type":"shot","img":"accessEvents","ken":"in","captions":[]},
    {"t0":91.57,"t1":96.58, "type":"cycle_precise",
        "words":[("GRANTED",92.13),("DENIED",93.06),("UNUSUAL",94.07),("INVESTIGATED",95.06)], "bgimg":"accessEvents"},
    {"t0":96.58,"t1":102.48,"type":"shot","img":"investigationTop","ken":"in",
        "captions":[("WHAT HAPPENED?",96.58,102.48)]},
    {"t0":102.48,"t1":107.33,"type":"shot","img":"investigationEvidence","ken":"panfull",
        "captions":[("WHAT THE SYSTEM KNEW.",102.48,107.33)]},
    {"t0":107.33,"t1":128.62,"type":"shot","img":"commandCenter","ken":"in",
        "captions":[
            ("SECURITY. AUTOMATION. ZONES. DEVICE HEALTH.",110.96,119.14),
            ("ONE OPERATIONAL PICTURE.",119.14,122.65),
            ("MORE THAN A DASHBOARD.",122.65,128.62),
        ]},
    {"t0":128.62,"t1":132.93,"type":"black","lines":["THE CAMPUS CAN SEE.","UNDERSTAND. DECIDE. ACT."]},
    {"t0":132.93,"t1":142.92,"type":"final"},
]
TOTAL = T[-1]["t1"]
N = len(T)

def build_black(i, cue, dur_render):
    filters = []
    for li, line in enumerate(cue["lines"]):
        tf = txtfile(f"black_{i}_{li}", line)
        delay = 0.4 + li*0.7
        filters.append(
            f"drawtext=fontfile={FONT_LIGHT}:textfile='{tf}':fontcolor={WHITE}:fontsize=56:"
            f"x=(w-text_w)/2:y=(h-text_h)/2+{li*84-42}:alpha='if(lt(t,{delay}),0,1)':enable='gte(t,{delay})'"
        )
    out = f"{SEGS}/seg_{i:02d}.mp4"
    vfilter = ",".join(filters) if filters else "null"
    cmd = ["ffmpeg","-y","-hide_banner","-loglevel","error","-f","lavfi",
           "-i", f"color=c=black:s={W}x{H}:r={FPS}:d={dur_render}",
           "-vf", vfilter, "-pix_fmt","yuv420p","-r",str(FPS), out]
    run(cmd)
    return out

def build_clip(i, cue, dur_render):
    out = f"{SEGS}/seg_{i:02d}.mp4"
    run(["ffmpeg","-y","-hide_banner","-loglevel","error","-i", f"{CLIPS}/{cue['file']}",
         "-vf", f"scale={W}:{H},fps={FPS},tpad=stop_mode=clone:stop_duration=1.0", "-t", f"{dur_render:.4f}",
         "-pix_fmt","yuv420p","-r",str(FPS), out])
    return out

def build_cycle_precise(i, cue, dur_render):
    dur = cue["t1"] - cue["t0"]
    words = cue["words"]
    filters = []
    bg = cue.get("bgimg")
    if bg:
        filters.append(f"scale={W}:-2,crop={W}:{H}")
        filters.append("boxblur=10:1")
        filters.append("eq=brightness=-0.32:saturation=0.7")
    n = len(words)
    for wi, (w, wt) in enumerate(words):
        local_t = wt - cue["t0"]
        tf = txtfile(f"cyc_{i}_{wi}", w)
        xpos = f"(w*{ (wi+0.5)/n })-text_w/2"
        filters.append(
            f"drawtext=fontfile={FONT_BOLD}:textfile='{tf}':fontsize=44:"
            f"fontcolor={DIM}:x='{xpos}':y=(h-text_h)/2:alpha=0.3:enable='lt(t,{local_t})'"
        )
        filters.append(
            f"drawtext=fontfile={FONT_BOLD}:textfile='{tf}':fontsize=44:"
            f"fontcolor={WHITE}:x='{xpos}':y=(h-text_h)/2:alpha=1.0:enable='gte(t,{local_t})':"
            f"box=1:boxcolor=0xB0202A@0.0"
        )
    out = f"{SEGS}/seg_{i:02d}.mp4"
    if bg:
        cmd = ["ffmpeg","-y","-hide_banner","-loglevel","error","-loop","1","-i", IMG[bg],
               "-t", str(dur_render), "-vf", ",".join(filters), "-pix_fmt","yuv420p","-r",str(FPS), out]
    else:
        cmd = ["ffmpeg","-y","-hide_banner","-loglevel","error","-f","lavfi",
               "-i", f"color=c=black:s={W}x{H}:r={FPS}:d={dur_render}",
               "-vf", ",".join(filters), "-pix_fmt","yuv420p","-r",str(FPS), out]
    run(cmd)
    return out

def build_reveal(i, cue, dur_render, final=False):
    filters = []
    if not final:
        filters.append(
            f"drawbox=x='(w/2)-(min(t/2.4,1)*380)':y=(h/2)-1:w='min(t/2.4,1)*760':h=2:color={RED}@0.9:t=fill:enable='lt(t,2.6)'"
        )
    appear = 2.5 if not final else 0.6
    tf1 = txtfile(f"rev_{i}_wm", "AIU SMART CAMPUS")
    filters.append(
        f"drawtext=fontfile={FONT_BOLD}:textfile='{tf1}':fontsize=74:fontcolor={WHITE}:"
        f"x=(w-text_w)/2:y=(h/2)-120:alpha='if(lt(t,{appear}),0,1)':enable='gte(t,{appear})'"
    )
    tf2 = txtfile(f"rev_{i}_sub1", "CYBER-PHYSICAL CONTROL SYSTEM")
    filters.append(
        f"drawtext=fontfile={FONT_LIGHT}:textfile='{tf2}':fontsize=34:fontcolor={DIM}:"
        f"x=(w-text_w)/2:y=(h/2)-24:alpha='if(lt(t,{appear}),0,1)':enable='gte(t,{appear})'"
    )
    if not final:
        tf3 = txtfile(f"rev_{i}_sub2", "Designed for Alamein International University.")
        filters.append(
            f"drawtext=fontfile={FONT_LIGHT}:textfile='{tf3}':fontsize=24:fontcolor={DIM}:"
            f"x=(w-text_w)/2:y=(h/2)+40:alpha='if(lt(t,{appear}),0,1)':enable='gte(t,{appear})'"
        )
    else:
        tf3 = txtfile(f"rev_{i}_sub2", "SEE.   UNDERSTAND.   DECIDE.   ACT.")
        filters.append(
            f"drawtext=fontfile={FONT_LIGHT}:textfile='{tf3}':fontsize=28:fontcolor={DIM}:"
            f"x=(w-text_w)/2:y=(h/2)+40:alpha='if(lt(t,{appear+1.6}),0,1)':enable='gte(t,{appear+1.6})'"
        )
        tf4 = txtfile(f"rev_{i}_sub3", "Designed for Alamein International University.")
        filters.append(
            f"drawtext=fontfile={FONT_LIGHT}:textfile='{tf4}':fontsize=20:fontcolor={DIM}:"
            f"x=(w-text_w)/2:y=(h/2)+90:alpha='if(lt(t,{appear+2.8}),0,1)':enable='gte(t,{appear+2.8})'"
        )
    out = f"{SEGS}/seg_{i:02d}.mp4"
    if not final:
        # continuity: the conceptual campus massing fades into a darkened, blurred backdrop for the title
        pre = ["scale=1920:1080,boxblur=14:2,eq=brightness=-0.42:saturation=0.55,"
               "drawbox=x=0:y=0:w=iw:h=ih:color=0x0B0B24@0.45:t=fill"]
        cmd = ["ffmpeg","-y","-hide_banner","-loglevel","error","-loop","1","-i", f"{CLIPS}/massing_last.png","-t", str(dur_render),
               "-vf", ",".join(pre + filters), "-pix_fmt","yuv420p","-r",str(FPS), out]
    else:
        cmd = ["ffmpeg","-y","-hide_banner","-loglevel","error","-f","lavfi",
               "-i", f"color=c=0x0B0B24:s={W}x{H}:r={FPS}:d={dur_render}",
               "-vf", ",".join(filters), "-pix_fmt","yuv420p","-r",str(FPS), out]
    run(cmd)
    return out

def caption_filters(cue, dur):
    """Render a list of (text,abs_start,abs_end) captions, fading in/out, never overlapping."""
    filters = []
    for ci, (text, a0, a1) in enumerate(cue.get("captions", [])):
        ls = a0 - cue["t0"]; le = a1 - cue["t0"]
        tf = txtfile(f"shot_{cue['_i']}_cap{ci}", text)
        alpha = (f"if(lt(t,{ls}),0,"
                 f"if(lt(t,{ls+0.3}),(t-{ls})/0.3,"
                 f"if(lt(t,{le-0.25}),1,"
                 f"if(lt(t,{le}),({le}-t)/0.25,0))))")
        enable = f"between(t,{ls},{le+0.05})"
        filters.append(
            f"drawtext=fontfile={FONT_BOLD}:textfile='{tf}':fontsize=42:fontcolor={WHITE}:"
            f"box=1:boxcolor=0x000000@0.42:boxborderw=20:"
            f"x=(w-text_w)/2:y=110:alpha='{alpha}':enable='{enable}'"
        )
    for si, (text, a0, a1) in enumerate(cue.get("subs", [])):
        ls = a0 - cue["t0"]; le = a1 - cue["t0"]
        tf = txtfile(f"shot_{cue['_i']}_sub{si}", text)
        alpha = (f"if(lt(t,{ls+0.3}),0,if(lt(t,{le}),1,0))")
        enable = f"between(t,{ls},{le+0.05})"
        filters.append(
            f"drawtext=fontfile={FONT_LIGHT}:textfile='{tf}':fontsize=20:fontcolor={DIM}:"
            f"x=(w-text_w)/2:y=h-80:alpha='{alpha}':enable='{enable}'"
        )
    return filters

def build_shot(i, cue, dur_render):
    dur = cue["t1"] - cue["t0"]
    img = IMG[cue["img"]]
    ken = cue.get("ken","in")
    tclamp = f"min(t\\,{dur})"
    if cue["img"] in SHORT_IMAGES:
        if ken == "zoom":
            base = [f"scale={W}:{H}:force_original_aspect_ratio=increase", f"crop={W}:{H}",
                    f"scale='iw*(1+0.06*{tclamp}/{dur})':-2:eval=frame",
                    f"crop={W}:{H}:'(iw-{W})/2':'(ih-{H})/2'"]
        else:
            base = [f"scale={W}:{H}:force_original_aspect_ratio=increase", f"crop={W}:{H}"]
    else:
        base = [f"scale={W}:-2"]
        if ken == "in":
            base.append(f"crop={W}:{H}:0:'min({tclamp}/{dur}*max(0\\,ih-{H})*0.4\\,max(0\\,ih-{H}))'")
        elif ken == "panfull":
            base.append(f"crop={W}:{H}:0:'min({tclamp}/{dur}*max(0\\,ih-{H})\\,max(0\\,ih-{H}))'")
        elif ken == "pan2":
            base.append(f"crop={W}:{H}:0:'max(0\\,ih-{H})*(0.35+0.20*min({tclamp}/{dur}\\,1))'")
        elif ken == "out":
            base.append(f"crop={W}:{H}:0:'max(0\\,ih-{H})*(1-min({tclamp}/{dur}\\,1))*0.3'")
        else:
            base.append(f"crop={W}:{H}:0:'max(0\\,ih-{H})*0.15'")
    filters = list(base)
    cue["_i"] = i
    filters += caption_filters(cue, dur)
    out = f"{SEGS}/seg_{i:02d}.mp4"
    cmd = ["ffmpeg","-y","-hide_banner","-loglevel","error","-loop","1","-i", img,
           "-t", str(dur_render), "-vf", ",".join(filters), "-pix_fmt","yuv420p","-r",str(FPS), out]
    run(cmd)
    return out

orig_dur = [round(c["t1"]-c["t0"], 6) for c in T]
seg_files = []
for i, cue in enumerate(T):
    dur_render = orig_dur[i] + (PAD if i < N-1 else 0.0)
    if cue["type"] == "black":
        f = build_black(i, cue, dur_render)
    elif cue["type"] == "cycle_precise":
        f = build_cycle_precise(i, cue, dur_render)
    elif cue["type"] == "clip":
        f = build_clip(i, cue, dur_render)
    elif cue["type"] == "reveal":
        f = build_reveal(i, cue, dur_render, final=False)
    elif cue["type"] == "final":
        f = build_reveal(i, cue, dur_render, final=True)
    elif cue["type"] == "shot":
        f = build_shot(i, cue, dur_render)
    seg_files.append(f)
    print(f"built segment {i}: {cue['type']} (orig {round(orig_dur[i],2)}s, rendered {round(dur_render,2)}s)")

# ---- Chain all segments with real crossfade dissolves (frame-padded so VO sync never drifts) ----
cum = []
running = 0.0
for d in orig_dur:
    running += d
    cum.append(running)

inputs = []
for sf in seg_files:
    inputs += ["-i", sf]

filter_parts = []
prev_label = "0:v"
for k in range(1, N):
    offset = cum[k-1] - orig_dur[0]*0 if k == 1 else cum[k-1]
    offset = cum[k-1]
    out_label = f"v{k}" if k < N-1 else "vout"
    filter_parts.append(
        f"[{prev_label}][{k}:v]xfade=transition=fade:duration={PAD}:offset={offset:.3f}[{out_label}]"
    )
    prev_label = out_label

filter_complex = ";".join(filter_parts)
video_out = f"{BUILD}/video_only3.mp4"
cmd = ["ffmpeg","-y","-hide_banner","-loglevel","error"] + inputs + [
    "-filter_complex", filter_complex, "-map","[vout]",
    "-c:v","libx264","-pix_fmt","yuv420p","-r",str(FPS),"-crf","18", video_out]
run(cmd)
print("VIDEO XFADE-CHAIN DONE:", video_out, "TOTAL:", TOTAL)
